# hyprlang noerror false
# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

exec-once = [workspace 1 silent] vivaldi
exec-once = [workspace 5 silent] discord
exec-once = [workspace 5 silent] kitty btop
exec-once = [workspace 8 silent] spotify && playctrl play

# Delay app starts to let QuickShell UI initialize first
exec-once = sleep 10 && discord
exec-once = sleep 15 && obsidian
exec-once = sleep 3 && spotify
exec-once = sleep 7 && playerctl -p spotify play && playerctl -p spotify volume 0.6

# Return to workspace 1 after apps finish starting
exec-once = hyprctl dispatch workspace 1

# TODO: temorary fix to address awake not working
exec-once = sleep 60 && pkill hypridle
