# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

exec-once = [workspace 5 silent] discord

# start spotify and initiate play
exec-once = [workspace 4 silent] spotify
exec-once = sleep 5 && playerctl play && playerctl volume 0.6

# Restart session target to ensure Home Manager services start properly
exec-once = systemctl --user restart hyprland-session.target