# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

exec-once = [workspace 5 silent] discord
exec-once = [workspace 4 silent] spotify && playctrl play

# Restart session target to ensure Home Manager services start properly
exec-once = systemctl --user restart hyprland-session.target

