# hyprlang noerror false
# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

######### Workspace rules ########
workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1

workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-1

workspace = 9, monitor:DP-1
workspace = 10, monitor:DP-1

######### Window rules ########
windowrule {
  name = wrkspc-obsidian
  match:class = obsidian
  workspace = 4 silent
  no_initial_focus = on
}

windowrule {
  name = wrkspc-spotify
  match:class = [Ss]potify
  workspace = 5 silent
  no_initial_focus = on
}

windowrule {
  name = wrkspc-discord
  match:class = discord
  workspace = 6 silent
  no_initial_focus = on
}

windowrule {
  name = wrkspc-steam
  match:class = steam
  workspace = 6 silent
  no_initial_focus = on
}
